---
# tasks file for get_hw_info

- name: install jq for redhat
  yum: name=jq state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes

- name: install jq for ubuntu
  apt: name=jq state=present
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- name: install jq for SLES
  zypper: name=jq state=present
  when: ansible_distribution == 'SLES'
  ignore_errors: yes

- name: install jq for CentOS
  yum: name=jq state=present disable_gpg_check=yes
  when: ansible_distribution == 'CentOS'
  ignore_errors: yes

- name: install ethtool for redhat
  yum: name=ethtool state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes

- name: install ethtool for ubuntu
  apt: name=ethtool state=present
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- name: install ethtool for SLES
  zypper: name=ethtool state=present
  when: ansible_distribution == 'SLES'
  ignore_errors: yes

- name: install ethtool for CentOS
  yum: name=ethtool state=present disable_gpg_check=yes
  when: ansible_distribution == 'CentOS'
  ignore_errors: yes

- name: install lshw for redhat
  yum: name=lshw state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes

- name: install lshw for ubuntu
  apt: name=lshw state=present
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- name: install lshw for SLES
  zypper: name=lshw state=present
  when: ansible_distribution == 'SLES'
  ignore_errors: yes

- name: install lshw for CentOS
  yum: name=lshw state=present disable_gpg_check=yes
  when: ansible_distribution == 'CentOS'
  ignore_errors: yes

- name: install lsblk for redhat
  yum: name=lsblk state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes

- name: install lsblk for ubuntu
  apt: name=lsblk state=present
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- name: install lsblk for CentOS
  yum: name=lsblk state=present disable_gpg_check=yes
  when: ansible_distribution == 'CentOS'
  ignore_errors: yes

- name: install dmidecode for redhat
  yum: name=dmidecode state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes

- name: install dmidecode for ubuntu
  apt: name=dmidecode state=present
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- name: install dmidecode for SLES
  zypper: name=dmidecode state=present
  when: ansible_distribution == 'SLES'
  ignore_errors: yes

- name: install dmidecode for CentOS
  yum: name=dmidecode state=present disable_gpg_check=yes
  when: ansible_distribution == 'CentOS'
  ignore_errors: yes

- name: copy config_info_run.sh file
  copy: src=config_info_run.sh dest=/tmp/config_info_run.sh mode=0755
- name: copy netinfo.py file
  copy: src=netinfo.py dest=/tmp/netinfo.py mode=0755
- name: copy hw-functions file
  copy: src=hw-functions dest=/tmp/hw-functions mode=0755

- name: install ansible
  shell: pip install ansible
  ignore_errors: yes
  become: true
  become_method: sudo
  become_user: root